### ISSUE TITLE
Deleting Criteria / Return CID (db.where)

### ISSUE THREAD

**Issue by Mischine** [twitch-irc/twitch-irc-db#1]
How can I delete an entry based on a different key/value? 

something like this.. ?
db.remove('monsters', name='dragon').then(function() {
    console.log('Item removed');
});

Or, is it possible to get the cid of a where statement?

db.where('monsters', {name: "sphinx"}).then(function(result) {
    console.log(result('cid'));
});

**Comment by Schmoopiie** [comment]
The result is an object, you can use ``console.log(result);`` if you want to see how the result is being displayed. If you want to delete a key, you will need to get it's cid (unless you already know it) and then delete it:

```javascript
db.where('monsters', {name: "sphinx"}).then(function(result) {
    if (result.items.length >= 1) {
        db.remove('monsters', result.items[0].cid).then(function() {
            console.log('Removed cid ' + result.items[0].cid);
        });
    }
});
```
